services:
  app:
    image: my-site:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - app-data:/app/data
      - app-uploads:/app/uploads
      # Optionally override built-in content with local posts:
      # - ./content:/app/content
    env_file:
      - .env.local

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiNmVkYWQ2NzQwNDgzZDVjMWVjODAzMTM5MTIzMmVlYmUiLCJ0IjoiNGIwNTZiN2UtNzAwYS00MjNiLTkyM2ItNGExOGJkZTQxMGIwIiwicyI6IllXWm1OelUxTWpjdE9EUXhOUzAwTnpWakxXSmhNekF0TjJZeU1EaGpZVEptT0Rnd05EQTFNelZqWmpFdE1qYzNOQzAwTlRFNUxUZzJaVFV0TlRsalptTTRPR014TWpsbCJ9
    restart: unless-stopped
    depends_on:
      - app

volumes:
  app-data:
  app-uploads:
